# Twitter config
TWITTER_TWEETS_ENDPOINT = "https://api.twitter.com/2/tweets"
TWITTER_API_KEY = ""
TWITTER_API_KEY_SECRET = ""
TWITTER_BEARER_TOKEN = ""
TWITTER_ACCESS_TOKEN = ""
TWITTER_ACCESS_TOKEN_SECRET = ""
TWITTER_CLIENT_ID = ""
TWITTER_CLIENT_SECRET = ""

# Fanbox config
FANBOX_URL = "https://sakuraoriko.fanbox.cc/"
FANBOX_ARTIST_CLASS_NAME = "cCIwou"
FANBOX_POST_CLASS_NAME = "hOOGVP"
FANBOX_SEEN_POST_FILENAME = "seen_posts.txt"

# CODE CONSTANTS
MAXIMUM_RETRY = 5
SCHEDULE_PER_MINUTE = 1
